### ISSUE TITLE
[Feat] 인기 검색어 컴포넌트 구현

### ISSUE THREAD

**Issue by csk6314** [he2e2/git-flow#3]
## 📌 작업 내용
인기 검색어 컴포넌트 구현

<br/>

## ✅ To-Do

- [x] 인기 검색어 아코디언 컴포넌트 제작
- [x] API 데이터 바인딩
- [x] 상품 리스트 추가

<br/>
